Add Multiple Target Support
2pai/instastory-monitor-telegram pull request #9
Opened 2021-03-10 10:05 UTC by YogaSakti

it's done UwU 🥴

2021-03-11 07:09 UTC, 2pai requested changes
Good works, maybe need a few improvements.

2021-03-11 07:09 UTC, 2pai commented on downloader.js
>              const dir = `./images/${content.path}`
can we make the path is group by username?
i.e. `./images/${content.username}/${content.path}. for more clarity. 
then, we didn't have to change the filename.

2021-03-11 08:50 UTC, YogaSakti commented on downloader.js
>              const dir = `./images/${content.path}`
okay

2021-03-12 03:57 UTC, 2pai commented on dispatcher.js
> +                    console.log("Success send " + story.id + " to " + data.chat.title || data.chat.username || data.chat.first_name || data.chat.last_name + " (" + data.chat.id + ")")
can we use `Success send  ${story.id} to ${data.chat.title || data.chat.username || data.chat.first_name || data.chat.last_name } ${data.chat.id  )` instead ?

2021-03-12 03:57 UTC, 2pai commented on dispatcher.js
> +                    console.log("Success send " + story.id + " to " + data.chat.title || data.chat.username || data.chat.first_name || data.chat.last_name + " (" + data.chat.id + ")")
idem

2021-03-12 03:57 UTC, 2pai commented
cc @YogaSakti

2021-03-12 04:19 UTC, 2pai approved these changes
LGTM

2021-03-12 04:20 UTC, merged